name: WTT WhatsApp every 6 min
on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN:  ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_API_KEY_SID: ${{ secrets.TWILIO_API_KEY_SID }}
          TWILIO_API_KEY_SECRET: ${{ secrets.TWILIO_API_KEY_SECRET }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
          ALWAYS_SEND: "false"   # change to "true" if you want to force-send every run
        run: python main.py
